# Generated by Django 4.2.5 on 2023-10-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'OBSERVADO'), ('aprobado', 'APROBADO'), ('rechazado', 'RECHAZADO')]),
        ),
    ]
