# Generated by Django 4.2.5 on 2023-11-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='nuevoPTF',
            field=models.FileField(blank=True, null=True, upload_to='uploads/nuevosTF/'),
        ),
        migrations.AlterField(
            model_name='instanciaevaluacion',
            name='descripcion',
            field=models.CharField(choices=[('COMISION DE SEGUIMIENTO', 'COMISION DE SEGUIMIENTO'), ('TRIBUNAL EVALUADOR', 'TRIBUNAL EVALUADOR'), ('TRABAJO FINAL BORRADOR', 'TRABAJO FINAL BORRADOR'), ('DEFENSA TRABAJO FINAL', 'DEFENSA TRABAJO FINAL'), ('FINALIZADO', 'FINALIZADO')]),
        ),
    ]
