# Generated by Django 4.2.5 on 2023-10-15 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='comision',
            name='departamento',
            field=models.CharField(choices=[('Informatica', 'Informatica'), ('Minas', 'Minas'), ('Electronica', 'Electronica'), ('Agrimensura', 'Agrimensura')], default='Informatica'),
        ),
        migrations.AddField(
            model_name='comision',
            name='descripcion',
            field=models.CharField(default='Comisión nueva'),
        ),
        migrations.AddField(
            model_name='comision',
            name='resolucion',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='defensa',
            name='acta',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='defensa',
            name='nota',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ComisionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField()),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_comision', to='gestion.comision')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comision_proyecto', to='gestion.proyecto')),
            ],
        ),
    ]
