# Generated by Django 4.2.5 on 2023-10-14 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comision',
            name='proyecto',
        ),
        migrations.AddField(
            model_name='comision',
            name='descripcion',
            field=models.CharField(default='Comisión nueva'),
        ),
        migrations.CreateModel(
            name='ComisionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_comision', to='gestion.comision')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comision_proyecto', to='gestion.proyecto')),
            ],
        ),
    ]
