# Generated by Django 4.2.5 on 2023-10-14 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='estado',
            field=models.CharField(choices=[('OBSERVADO', 'OBSERVADO'), ('APROBADO', 'APROBADO'), ('RECHAZADO', 'RECHAZADO')]),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='instancia_evaluacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='instancia_evaluacion', to='gestion.instanciaevaluacion'),
        ),
        migrations.AlterField(
            model_name='instanciaevaluacion',
            name='descripcion',
            field=models.CharField(choices=[('COMISION DE SEGUIMIENTO', 'COMISION DE SEGUIMIENTO'), ('TRIBUNAL EVALUADOR', 'TRIBUNAL EVALUADOR'), ('DEFENSA TRABAJO FINAL', 'DEFENSA TRABAJO FINAL'), ('FINALIZADO', 'FINALIZADO')]),
        ),
        migrations.AlterField(
            model_name='tribunal',
            name='numero_disposicion',
            field=models.CharField(max_length=50),
        ),
    ]
