# Generated by Django 4.2.5 on 2023-11-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_evaluacion_nuevoptf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='nuevoPTF',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
