# Generated by Django 4.2.5 on 2023-10-15 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_comision_proyecto_comision_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionproyecto',
            name='comision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_comision', to='gestion.comision'),
        ),
    ]
