# Generated by Django 4.2.5 on 2023-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_evaluacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanciaevaluacion',
            name='descripcion',
            field=models.CharField(choices=[('COMISION DE SEGUIMIENTO', 'COMISION DE SEGUIMIENTO'), ('TRIBUNAL EVALUADOR', 'TRIBUNAL EVALUADOR'), ('DEFENSA TRABAJO FINAL', 'DEFENSA TRABAJO FINAL'), ('FINALIZADO', 'FINALIZADO')]),
        ),
    ]
