# Generated by Django 4.2.5 on 2023-10-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_comisionproyecto_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comisionproyecto',
            name='comision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_comision', to='gestion.comision'),
        ),
        migrations.AlterField(
            model_name='comisionproyecto',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comision_proyecto', to='gestion.proyecto'),
        ),
    ]
