# Generated by Django 4.2.5 on 2023-11-01 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=15, null=True)),
                ('asesor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_asesor', to='persona.asesor')),
                ('docente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_docente', to='persona.docente')),
                ('estudiante', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_estudiante', to='persona.estudiante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='persona_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estudiante_usuario', to='persona.estudiante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estudiante_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='docente_usuario', to='persona.docente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='docente_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asesor_usuario', to='persona.asesor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asesor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
