# Generated by Django 4.2.5 on 2023-10-13 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cuil', models.CharField(max_length=12)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=45)),
                ('telefono', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('cv', models.FileField(upload_to='uploads/')),
            ],
            bases=('persona.persona',),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
            ],
            bases=('persona.persona',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('matricula', models.CharField(max_length=12)),
            ],
            bases=('persona.persona',),
        ),
        migrations.CreateModel(
            name='RolTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('presidente', 'PRESIDENTE'), ('vocal', 'VOCAL'), ('vocal_suplente', 'VOCAL SUPLENTE')])),
                ('tribunal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tribunal', to='gestion.tribunal')),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='docente_tribunal', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='RolProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('director', 'DIRECTOR'), ('codirector', 'CODIRECTOR')])),
                ('fecha_alta', models.DateField(blank=True)),
                ('fecha_baja', models.DateField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto', to='gestion.proyecto')),
                ('docente', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='docente_proyecto', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(blank=True)),
                ('fecha_baja', models.DateField(blank=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_integrante', to='gestion.proyecto')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estudiante', to='persona.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comision', to='gestion.comision')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrante_comision', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='AsesorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesor_proyecto', to='gestion.proyecto')),
                ('asesor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asesor', to='persona.asesor')),
            ],
        ),
    ]
