# Generated by Django 4.2.5 on 2023-11-01 01:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cuil', models.CharField(max_length=12)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('cv', models.FileField(upload_to='uploads/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cuil', models.CharField(max_length=12)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cuil', models.CharField(max_length=12)),
                ('dni', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=45)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('matricula', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolTribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('Presidente', 'Presidente'), ('Vocal', 'Vocal'), ('Vocal suplente', 'Vocal suplente')])),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(default=datetime.date(9999, 12, 31))),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docente_tribunal', to='persona.docente')),
                ('tribunal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribunal', to='gestion.tribunal')),
            ],
        ),
        migrations.CreateModel(
            name='RolProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(choices=[('Director', 'Director'), ('Codirector', 'Codirector')])),
                ('fecha_alta', models.DateField(blank=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docente_proyecto', to='persona.docente')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto', to='gestion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(blank=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiante', to='persona.estudiante')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto_integrante', to='gestion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='IntegranteComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comision', to='gestion.comision')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrante_comision', to='persona.docente')),
            ],
        ),
        migrations.CreateModel(
            name='AsesorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesor', to='persona.asesor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesor_proyecto', to='gestion.proyecto')),
            ],
        ),
    ]
