# Generated by Django 4.2.5 on 2023-10-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantecomision',
            name='descripcion',
            field=models.CharField(default='Comisión nueva'),
        ),
        migrations.AlterField(
            model_name='integranteproyecto',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiante', to='persona.estudiante'),
        ),
    ]
