# Generated by Django 4.2.5 on 2023-10-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_integrantecomision_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrantecomision',
            name='descripcion',
        ),
    ]
