# Generated by Django 4.2.5 on 2023-10-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_integranteproyecto_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolproyecto',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
