# Generated by Django 4.2.5 on 2023-10-13 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_rolproyecto_fecha_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolproyecto',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docente_proyecto', to='persona.docente'),
        ),
    ]
