# Generated by Django 4.2.5 on 2023-10-14 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_remove_integrantecomision_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrantecomision',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
