# Generated by Django 4.2.5 on 2023-10-15 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_integrantecomision_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='roltribunal',
            name='fecha_alta',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
