# Generated by Django 4.2.5 on 2023-10-13 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
        ('persona', '0005_alter_asesorproyecto_asesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roltribunal',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docente_tribunal', to='persona.docente'),
        ),
        migrations.AlterField(
            model_name='roltribunal',
            name='tribunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tribunal', to='gestion.tribunal'),
        ),
    ]
