# Generated by Django 4.2.5 on 2023-10-15 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_roltribunal_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='roltribunal',
            name='fecha_baja',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
    ]
