# Generated by Django 4.2.5 on 2023-10-13 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_roltribunal_docente_alter_roltribunal_tribunal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorproyecto',
            name='asesor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asesor', to='persona.asesor'),
        ),
        migrations.AlterField(
            model_name='rolproyecto',
            name='descripcion',
            field=models.CharField(choices=[('Director', 'Director'), ('Codirector', 'Codirector')]),
        ),
        migrations.AlterField(
            model_name='roltribunal',
            name='descripcion',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('Vocal', 'Vocal'), ('Vocal suplente', 'Vocal suplente')]),
        ),
    ]
