# Generated by Django 4.2.5 on 2023-10-13 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_alter_asesorproyecto_asesor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesorproyecto',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asesor', to='persona.asesor'),
        ),
    ]
