# Generated by Django 4.2.5 on 2023-10-04 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cuil', models.IntegerField()),
                ('fecha_alta', models.DateTimeField(blank=True)),
                ('fecha_baja', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('proyecto_escrito', models.FileField(upload_to='')),
                ('certificado_analítico', models.FileField(upload_to='')),
                ('nota_director', models.FileField(upload_to='')),
                ('cv', models.FileField(upload_to='')),
                ('estado', models.CharField(choices=[('pendiente', 'PENDIENTE'), ('observado', 'OBSERVADO'), ('rechazado', 'RECHAZADO')])),
                ('codirector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codirector', to='cstf.docente')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='director', to='cstf.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.IntegerField()),
                ('matricula', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=45)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyecto', to='cstf.proyecto')),
            ],
        ),
    ]
