# Generated by Django 4.2.5 on 2023-10-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cstf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='fecha_alta',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_baja',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiante_proyecto', to='cstf.proyecto'),
        ),
        migrations.CreateModel(
            name='Tribunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposicion', models.FileField(upload_to='')),
                ('fecha_disposicion', models.DateField()),
                ('numero_disposicion', models.IntegerField()),
                ('miembros', models.ManyToManyField(related_name='miembros', to='cstf.docente')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tribunal_proyecto', to='cstf.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrador', models.FileField(upload_to='')),
                ('aceptacion_director', models.FileField(upload_to='')),
                ('fecha_presentacion', models.DateField(auto_now_add=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tf_proyecto', to='cstf.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_entrega', models.DateField(auto_now_add=True)),
                ('arch_evaluacion', models.FileField(upload_to='')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='informe_proyecto', to='cstf.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionTF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe', models.FileField(upload_to='')),
                ('fecha', models.DateField()),
                ('trabajo_final', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluacion_tf', to='cstf.trabajofinal')),
            ],
        ),
        migrations.CreateModel(
            name='Defensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nota', models.IntegerField(blank=True)),
                ('trabajo_final', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='defensa_tf', to='cstf.trabajofinal')),
            ],
        ),
    ]
